### PR TITLE
GO111MODULE=off while installing errcheck + switch to go mod

### PR DESCRIPTION
**Pull request by viktorbenei**
Running `go get` with `GO111MODULE=off` set, so if you run this step in a go module directory it'll still install `errcheck` to PATH.

### CODE REVIEW

**Comment by viktorbenei** [comment]
Build failed due to https://github.com/bitrise-steplib/steps-go-list/issues/2

**Comment by viktorbenei** [comment]
Workaround implementation: https://github.com/bitrise-steplib/steps-errcheck/pull/6

**Comment by viktorbenei** [comment]
Alternatively we could change the workdir to `/tmp` or such, so when `go get` is called it won't install it in our own module but will install it "globally".

**Comment by godrei** [comment]
Hi @viktorbenei ,

build fails with this error:

```
Configs:
- packages: github.com/bitrise-steplib/steps-errcheck
Installing golint
$ go "get" "-u" "golang.org/x/lint/golint"
Running golint...
$ golint "-set_exit_status" "github.com/bitrise-steplib/steps-errcheck"
golint failed
go/build: go list github.com/bitrise-steplib/steps-errcheck: exit status 1
go: inconsistent vendoring in /bitrise/go/src/github.com/bitrise-steplib/steps-errcheck:
	golang.org/x/lint@v0.0.0-20200302205851-738671d3881b: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/tools@v0.0.0-20201121010211-780cb80bd7fb: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
golint failed: %!s(<nil>)
```

It fails by the lack of a global dependency install option: https://github.com/golang/go/issues/30515.

I agree with you, each step installing a go dependency via `go get ...`, should run the install cmd in a tmp dir / outside of the actual module.

I create a ticket to solve this.

**Comment by imrekel** [comment]
so, running go get in `/` (outside of any module) solves the issue. Since it affects both `golint` and this step itself, I had to run the validation with both of them fixed. I did this by pinning the errcheck run to the branch of this PR and using a temporary repo with the `golint` fix. See the green run: https://app.bitrise.io/build/6fff197794d38d3d#?tab=log

After removing the references to the fixes it fails again but can be merged as the issue will be fixed if both this and the new golint get released.

**Review by trapacska — APPROVED** [review]

**Comment by viktorbenei** [comment]
Thanks everyone! :)

**Pull request merged**
